import type { Address } from '@core/models';

/**
 * Address seed records.
 *
 * Postcodes and phone numbers come from the ranges reserved for documentation and
 * fiction, so nothing here routes to a real household. Includes a customer with
 * separate shipping and billing addresses, and one with none at all, since both are
 * cases a checkout has to handle.
 */
export const ADDRESS_SEEDS: readonly Address[] = [
  {
    id: 'adr-0001',
    userId: 'usr-1001',
    type: 'shipping',
    label: 'Home',
    recipient: 'Ananya Iyer',
    line1: '48 MG Road',
    line2: 'Flat 3B, Sunshine Towers',
    city: 'Bengaluru',
    region: 'Karnataka',
    postcode: '560001',
    countryCode: 'IN',
    phone: '+91 98450 90014',
    isDefault: true,
  },
  {
    id: 'adr-0002',
    userId: 'usr-1001',
    type: 'billing',
    label: 'Billing',
    recipient: 'Ananya Iyer',
    line1: '48 MG Road',
    line2: 'Flat 3B, Sunshine Towers',
    city: 'Bengaluru',
    region: 'Karnataka',
    postcode: '560001',
    countryCode: 'IN',
    phone: '+91 98450 90014',
    isDefault: true,
  },
  {
    id: 'adr-0003',
    userId: 'usr-1001',
    type: 'shipping',
    label: 'Work',
    recipient: 'Ananya Iyer, c/o Tech Park Reception',
    line1: 'Prestige Tech Park',
    line2: 'Outer Ring Road, Marathahalli',
    city: 'Bengaluru',
    region: 'Karnataka',
    postcode: '560103',
    countryCode: 'IN',
    phone: '+91 80 4960 0022',
    isDefault: false,
  },
  {
    id: 'adr-0004',
    userId: 'usr-1002',
    type: 'shipping',
    label: 'Home',
    recipient: 'Rohan Verma',
    line1: '7 Larkfield Enclave',
    line2: 'Golf Course Road',
    city: 'Gurugram',
    region: 'Haryana',
    postcode: '122002',
    countryCode: 'IN',
    phone: '+91 99100 90031',
    isDefault: true,
  },
  {
    id: 'adr-0005',
    userId: 'usr-1002',
    type: 'billing',
    label: 'Parents’ address',
    recipient: 'Rohan Verma',
    line1: '221 Halston Villa',
    line2: 'Civil Lines',
    city: 'Jaipur',
    region: 'Rajasthan',
    postcode: '302006',
    countryCode: 'IN',
    phone: null,
    isDefault: true,
  },
  {
    id: 'adr-0006',
    userId: 'usr-1003',
    type: 'shipping',
    label: 'Home',
    recipient: 'Priya Raman',
    line1: '15 Anna Salai',
    line2: 'T. Nagar',
    city: 'Chennai',
    region: 'Tamil Nadu',
    postcode: '600017',
    countryCode: 'IN',
    phone: null,
    isDefault: true,
  },
  {
    id: 'adr-0007',
    userId: 'usr-1003',
    type: 'billing',
    label: 'Home',
    recipient: 'Priya Raman',
    line1: '15 Anna Salai',
    line2: 'T. Nagar',
    city: 'Chennai',
    region: 'Tamil Nadu',
    postcode: '600017',
    countryCode: 'IN',
    phone: null,
    isDefault: true,
  },
  {
    id: 'adr-0008',
    userId: 'usr-1004',
    type: 'shipping',
    label: 'Home',
    recipient: 'Vikram Malhotra',
    line1: 'A-12 Neeti Bagh',
    line2: 'Second Floor',
    city: 'New Delhi',
    region: 'Delhi',
    postcode: '110049',
    countryCode: 'IN',
    phone: '+91 98110 40880',
    isDefault: true,
  },
  {
    id: 'adr-0009',
    userId: 'usr-1004',
    type: 'billing',
    label: 'Home',
    recipient: 'Vikram Malhotra',
    line1: 'A-12 Neeti Bagh',
    line2: 'Second Floor',
    city: 'New Delhi',
    region: 'Delhi',
    postcode: '110049',
    countryCode: 'IN',
    phone: '+91 98110 40880',
    isDefault: true,
  },
  {
    id: 'adr-0010',
    userId: 'usr-1005',
    type: 'shipping',
    label: 'Home',
    recipient: 'Neha Gupta',
    line1: '92 Marine Drive',
    line2: 'Flat 12B, Nariman Point',
    city: 'Mumbai',
    region: 'Maharashtra',
    postcode: '400021',
    countryCode: 'IN',
    phone: '+91 98200 90090',
    isDefault: true,
  },
  {
    id: 'adr-0011',
    userId: 'usr-1005',
    type: 'billing',
    label: 'Home',
    recipient: 'Neha Gupta',
    line1: '92 Marine Drive',
    line2: 'Flat 12B, Nariman Point',
    city: 'Mumbai',
    region: 'Maharashtra',
    postcode: '400021',
    countryCode: 'IN',
    phone: '+91 98200 90090',
    isDefault: true,
  },
];
