import type { Address } from '@core/models';

/**
 * Address seed records.
 *
 * Postcodes and phone numbers come from the ranges reserved for documentation and
 * fiction, so nothing here routes to a real household. Includes a customer with
 * separate shipping and billing addresses, and one with none at all, since both are
 * cases a checkout has to handle.
 */
export const ADDRESS_SEEDS: readonly Address[] = [
  {
    id: 'adr-0001',
    userId: 'usr-1001',
    type: 'shipping',
    label: 'Home',
    recipient: 'Harriet Vance',
    line1: '48 Bramble Court',
    line2: 'Flat 3',
    city: 'Bristol',
    region: 'Bristol',
    postcode: 'BS1 4TR',
    countryCode: 'GB',
    phone: '+44 7700 900142',
    isDefault: true,
  },
  {
    id: 'adr-0002',
    userId: 'usr-1001',
    type: 'billing',
    label: 'Billing',
    recipient: 'Harriet Vance',
    line1: '48 Bramble Court',
    line2: 'Flat 3',
    city: 'Bristol',
    region: 'Bristol',
    postcode: 'BS1 4TR',
    countryCode: 'GB',
    phone: '+44 7700 900142',
    isDefault: true,
  },
  {
    id: 'adr-0003',
    userId: 'usr-1001',
    type: 'shipping',
    label: 'Work',
    recipient: 'Harriet Vance, c/o Reception',
    line1: 'Kingsmead House',
    line2: '112 Redcliff Street',
    city: 'Bristol',
    region: 'Bristol',
    postcode: 'BS1 6HU',
    countryCode: 'GB',
    phone: '+44 117 496 0022',
    isDefault: false,
  },
  {
    id: 'adr-0004',
    userId: 'usr-1002',
    type: 'shipping',
    label: 'Home',
    recipient: 'Declan Moore',
    line1: '7 Larkfield Terrace',
    line2: null,
    city: 'Leeds',
    region: 'West Yorkshire',
    postcode: 'LS6 2AB',
    countryCode: 'GB',
    phone: '+44 7700 900318',
    isDefault: true,
  },
  {
    id: 'adr-0005',
    userId: 'usr-1002',
    type: 'billing',
    label: 'Parents’ address',
    recipient: 'Declan Moore',
    line1: '221 Halston Road',
    line2: null,
    city: 'Sheffield',
    region: 'South Yorkshire',
    postcode: 'S7 1QN',
    countryCode: 'GB',
    phone: null,
    isDefault: true,
  },
  {
    id: 'adr-0006',
    userId: 'usr-1003',
    type: 'shipping',
    label: 'Home',
    recipient: 'Priya Raman',
    line1: '15 Ashcombe Gardens',
    line2: null,
    city: 'Edinburgh',
    region: 'Midlothian',
    postcode: 'EH10 4LS',
    countryCode: 'GB',
    phone: null,
    isDefault: true,
  },
  {
    id: 'adr-0007',
    userId: 'usr-1003',
    type: 'billing',
    label: 'Home',
    recipient: 'Priya Raman',
    line1: '15 Ashcombe Gardens',
    line2: null,
    city: 'Edinburgh',
    region: 'Midlothian',
    postcode: 'EH10 4LS',
    countryCode: 'GB',
    phone: null,
    isDefault: true,
  },
  {
    id: 'adr-0008',
    userId: 'usr-1004',
    type: 'shipping',
    label: 'Home',
    recipient: 'Tomas Eriksen',
    line1: 'Nygade 12',
    line2: '2. sal',
    city: 'Copenhagen',
    region: 'Hovedstaden',
    postcode: '1164',
    countryCode: 'DK',
    phone: '+45 32 12 40 88',
    isDefault: true,
  },
  {
    id: 'adr-0009',
    userId: 'usr-1004',
    type: 'billing',
    label: 'Home',
    recipient: 'Tomas Eriksen',
    line1: 'Nygade 12',
    line2: '2. sal',
    city: 'Copenhagen',
    region: 'Hovedstaden',
    postcode: '1164',
    countryCode: 'DK',
    phone: '+45 32 12 40 88',
    isDefault: true,
  },
  {
    id: 'adr-0010',
    userId: 'usr-1005',
    type: 'shipping',
    label: 'Home',
    recipient: 'Nadia Okafor',
    line1: '92 Sefton Park Road',
    line2: null,
    city: 'Liverpool',
    region: 'Merseyside',
    postcode: 'L8 3SD',
    countryCode: 'GB',
    phone: '+44 7700 900904',
    isDefault: true,
  },
  {
    id: 'adr-0011',
    userId: 'usr-1005',
    type: 'billing',
    label: 'Home',
    recipient: 'Nadia Okafor',
    line1: '92 Sefton Park Road',
    line2: null,
    city: 'Liverpool',
    region: 'Merseyside',
    postcode: 'L8 3SD',
    countryCode: 'GB',
    phone: '+44 7700 900904',
    isDefault: true,
  },
];
