import type { ProductLifecycle, ProductSpecification } from '@core/models';

/**
 * Product seed records: the catalogue as a database would hold it.
 *
 * Deliberately *not* the API resource shape. Three things are absent because they are
 * derived rather than stored:
 *
 * - `stock`, which the API computes from inventory plus lifecycle;
 * - `rating`, computed from {@link ProductSeed.ratingDistribution} so the average can
 *   never contradict the histogram beneath it;
 * - `images` and `relatedProductIds`, generated from the slug and category.
 *
 * Storing any of those twice is how a catalogue starts lying about itself.
 *
 * Prices are integer pence. Brands are fictional; see `brands.mock.ts`.
 */
export interface ProductSeed {
  readonly id: string;
  readonly slug: string;
  readonly name: string;
  readonly brandId: string;
  readonly categoryId: string;
  readonly sku: string;
  readonly summary: string;
  readonly description: string;
  readonly priceMinor: number;
  /** Present only on reduced items. */
  readonly compareAtMinor?: number;
  readonly lifecycle: ProductLifecycle;
  readonly tags: readonly string[];
  readonly specifications: readonly ProductSpecification[];
  readonly weightGrams: number;
  readonly warrantyMonths: number;
  /** Review counts for 1 through 5 stars. All zeros means no reviews yet. */
  readonly ratingDistribution: readonly [number, number, number, number, number];
  /** ISO 8601. Drives the "new" badge and newest-first sorting. */
  readonly createdAt: string;
  readonly isFeatured: boolean;
}

export const PRODUCT_SEEDS: readonly ProductSeed[] = [
  // ==================== Headphones ====================
  {
    id: 'prd-0001',
    slug: 'aurelia-studio-one-open-back',
    name: 'Aurelia Studio One Open-Back',
    brandId: 'brd-aurelia',
    categoryId: 'cat-headphones',
    sku: 'AUR-SO1-OB',
    summary: 'Open-back reference headphones with a replaceable cable and earpads.',
    description:
      'The Studio One is Aurelia’s long-running mixing reference, tuned flat enough that it is unflattering by design. The open-back housing gives a wide stereo image at the cost of isolation, so it suits a quiet room rather than a commute. Every part down to the headband padding is sold separately as a spare.',
    priceMinor: 32900,
    lifecycle: 'active',
    tags: ['wired', 'open-back', 'studio', 'replaceable-parts'],
    specifications: [
      { label: 'Driver', value: '45 mm dynamic' },
      { label: 'Impedance', value: '250 Ω' },
      { label: 'Frequency response', value: '5 Hz – 35 kHz' },
      { label: 'Cable', value: '3 m detachable, 6.35 mm' },
    ],
    weightGrams: 340,
    warrantyMonths: 24,
    ratingDistribution: [2, 3, 11, 46, 138],
    createdAt: '2024-03-12T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0002',
    slug: 'aurelia-studio-one-closed',
    name: 'Aurelia Studio One Closed',
    brandId: 'brd-aurelia',
    categoryId: 'cat-headphones',
    sku: 'AUR-SO1-CL',
    summary: 'The Studio One tuning in a closed housing for tracking and noisy rooms.',
    description:
      'A closed-back sibling to the open Studio One, intended for recording where bleed into a microphone matters. Isolation is around 18 dB, and the tuning holds close to the open model above 200 Hz. Uses the same earpads and cables.',
    priceMinor: 29900,
    lifecycle: 'active',
    tags: ['wired', 'closed-back', 'studio', 'replaceable-parts'],
    specifications: [
      { label: 'Driver', value: '45 mm dynamic' },
      { label: 'Impedance', value: '80 Ω' },
      { label: 'Isolation', value: '18 dB passive' },
      { label: 'Cable', value: '3 m detachable, 6.35 mm' },
    ],
    weightGrams: 365,
    warrantyMonths: 24,
    ratingDistribution: [1, 2, 8, 39, 74],
    createdAt: '2024-03-12T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0003',
    slug: 'aurelia-meridian-anc',
    name: 'Aurelia Meridian ANC',
    brandId: 'brd-aurelia',
    categoryId: 'cat-headphones',
    sku: 'AUR-MRD-ANC',
    summary: 'Wireless over-ear with adaptive noise cancelling and 40-hour battery.',
    description:
      'Aurelia’s first serious attempt at travel headphones, pairing their house tuning with hybrid noise cancelling that adjusts to cabin noise. Charges over USB-C and can run wired with the cancelling switched off entirely, which keeps them useful once the battery eventually degrades.',
    priceMinor: 44900,
    compareAtMinor: 49900,
    lifecycle: 'active',
    tags: ['wireless', 'noise-cancelling', 'travel', 'usb-c'],
    specifications: [
      { label: 'Battery life', value: '40 hours, ANC on' },
      { label: 'Bluetooth', value: '5.3, LDAC and AAC' },
      { label: 'Charging', value: 'USB-C, 10 min for 5 hours' },
      { label: 'Weight', value: '278 g' },
    ],
    weightGrams: 278,
    warrantyMonths: 24,
    ratingDistribution: [4, 6, 18, 71, 164],
    createdAt: '2025-09-04T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0004',
    slug: 'kestrel-drift-over-ear',
    name: 'Kestrel Drift Over-Ear',
    brandId: 'brd-kestrel',
    categoryId: 'cat-headphones',
    sku: 'KES-DRF-OE',
    summary: 'Everyday wireless over-ear headphones with a 60-hour battery.',
    description:
      'The Drift trades outright noise cancelling depth for endurance, running about 60 hours between charges. Folds flat rather than into a ball, so it sits in a laptop bag without a case. Multipoint pairing holds two devices at once.',
    priceMinor: 17900,
    lifecycle: 'active',
    tags: ['wireless', 'long-battery', 'multipoint', 'foldable'],
    specifications: [
      { label: 'Battery life', value: '60 hours' },
      { label: 'Bluetooth', value: '5.2, multipoint' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Foldable', value: 'Flat only' },
    ],
    weightGrams: 255,
    warrantyMonths: 24,
    ratingDistribution: [6, 9, 27, 88, 121],
    createdAt: '2025-02-18T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0005',
    slug: 'kestrel-drift-lite',
    name: 'Kestrel Drift Lite',
    brandId: 'brd-kestrel',
    categoryId: 'cat-headphones',
    sku: 'KES-DRF-LT',
    summary: 'Lighter, cheaper Drift without the multipoint radio.',
    description:
      'Same drivers and tuning as the Drift in a simpler chassis, dropping multipoint pairing and the carry pouch. Battery life is unchanged at roughly 60 hours.',
    priceMinor: 11900,
    lifecycle: 'active',
    tags: ['wireless', 'long-battery', 'budget'],
    specifications: [
      { label: 'Battery life', value: '58 hours' },
      { label: 'Bluetooth', value: '5.2' },
      { label: 'Charging', value: 'USB-C' },
    ],
    weightGrams: 232,
    warrantyMonths: 12,
    ratingDistribution: [8, 14, 41, 96, 77],
    createdAt: '2025-06-11T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0006',
    slug: 'aurelia-foldaway-40',
    name: 'Aurelia Foldaway 40',
    brandId: 'brd-aurelia',
    categoryId: 'cat-headphones',
    sku: 'AUR-FA40',
    summary: 'On-ear wired headphones that collapse into a jacket pocket.',
    description:
      'A deliberately simple wired on-ear with no battery and no app. The hinges are steel and rated for 20,000 folds, which is the only specification Aurelia advertises about them.',
    priceMinor: 8900,
    lifecycle: 'discontinued',
    tags: ['wired', 'on-ear', 'portable'],
    specifications: [
      { label: 'Driver', value: '32 mm dynamic' },
      { label: 'Impedance', value: '32 Ω' },
      { label: 'Cable', value: '1.2 m fixed, 3.5 mm' },
    ],
    weightGrams: 168,
    warrantyMonths: 12,
    ratingDistribution: [3, 5, 14, 31, 28],
    createdAt: '2024-01-22T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Earbuds ====================
  {
    id: 'prd-0007',
    slug: 'kestrel-pip-pro',
    name: 'Kestrel Pip Pro',
    brandId: 'brd-kestrel',
    categoryId: 'cat-earbuds',
    sku: 'KES-PIP-PRO',
    summary: 'Noise cancelling earbuds with a wireless charging case.',
    description:
      'The Pip Pro adds hybrid noise cancelling and a wireless charging case to Kestrel’s in-ear line. Four tip sizes are included, and replacement tips are sold in packs rather than bundled with a whole new set.',
    priceMinor: 14900,
    lifecycle: 'active',
    tags: ['wireless', 'noise-cancelling', 'ipx4', 'wireless-charging'],
    specifications: [
      { label: 'Battery life', value: '8 hours, 32 with case' },
      { label: 'Water resistance', value: 'IPX4' },
      { label: 'Charging', value: 'USB-C and Qi' },
      { label: 'Tips included', value: 'XS, S, M, L' },
    ],
    weightGrams: 52,
    warrantyMonths: 24,
    ratingDistribution: [11, 18, 44, 132, 246],
    createdAt: '2025-11-20T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0008',
    slug: 'kestrel-pip',
    name: 'Kestrel Pip',
    brandId: 'brd-kestrel',
    categoryId: 'cat-earbuds',
    sku: 'KES-PIP',
    summary: 'Compact earbuds without noise cancelling.',
    description:
      'The standard Pip keeps the fit and the case of the Pro but leaves out noise cancelling and wireless charging. Battery life is slightly better as a result.',
    priceMinor: 8900,
    lifecycle: 'active',
    tags: ['wireless', 'ipx4', 'compact'],
    specifications: [
      { label: 'Battery life', value: '9 hours, 36 with case' },
      { label: 'Water resistance', value: 'IPX4' },
      { label: 'Charging', value: 'USB-C' },
    ],
    weightGrams: 46,
    warrantyMonths: 24,
    ratingDistribution: [9, 16, 52, 141, 118],
    createdAt: '2025-04-08T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0009',
    slug: 'aurelia-cadence-buds',
    name: 'Aurelia Cadence Buds',
    brandId: 'brd-aurelia',
    categoryId: 'cat-earbuds',
    sku: 'AUR-CAD-BD',
    summary: 'In-ear monitors with a balanced armature driver and detachable cable.',
    description:
      'Wired in-ear monitors aimed at musicians using them on stage. The cable detaches at the ear with a standard two-pin connector, so a snagged lead is a cheap replacement rather than a dead pair.',
    priceMinor: 19900,
    lifecycle: 'active',
    tags: ['wired', 'in-ear-monitor', 'stage', 'replaceable-parts'],
    specifications: [
      { label: 'Driver', value: 'Single balanced armature' },
      { label: 'Impedance', value: '18 Ω' },
      { label: 'Connector', value: 'Detachable 2-pin, 3.5 mm' },
      { label: 'Isolation', value: '26 dB' },
    ],
    weightGrams: 28,
    warrantyMonths: 24,
    ratingDistribution: [1, 3, 9, 24, 61],
    createdAt: '2024-08-30T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0010',
    slug: 'kestrel-sprint-sport-buds',
    name: 'Kestrel Sprint Sport Buds',
    brandId: 'brd-kestrel',
    categoryId: 'cat-earbuds',
    sku: 'KES-SPR-SB',
    summary: 'Ear-hook buds rated IP68 for running and the gym.',
    description:
      'Fixed ear hooks rather than tips, which stay put during a run at the cost of packing bulk. Rated IP68, so rinsing them under a tap is expected rather than risky.',
    priceMinor: 6900,
    compareAtMinor: 7900,
    lifecycle: 'active',
    tags: ['wireless', 'ip68', 'sport', 'ear-hook'],
    specifications: [
      { label: 'Battery life', value: '10 hours' },
      { label: 'Water resistance', value: 'IP68' },
      { label: 'Fit', value: 'Fixed ear hook' },
    ],
    weightGrams: 61,
    warrantyMonths: 12,
    ratingDistribution: [14, 21, 38, 74, 92],
    createdAt: '2025-05-27T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Speakers ====================
  {
    id: 'prd-0011',
    slug: 'aurelia-alcove-bookshelf-pair',
    name: 'Aurelia Alcove Bookshelf Pair',
    brandId: 'brd-aurelia',
    categoryId: 'cat-speakers',
    sku: 'AUR-ALC-BP',
    summary: 'Two-way passive bookshelf speakers, sold as a matched pair.',
    description:
      'A sealed two-way cabinet meant to sit close to a rear wall, which is unusual and makes them workable in a small room. Passive, so they need an amplifier. Grilles are magnetic and the drivers are field-replaceable.',
    priceMinor: 54900,
    lifecycle: 'active',
    tags: ['passive', 'bookshelf', 'pair', 'replaceable-parts'],
    specifications: [
      { label: 'Configuration', value: '2-way sealed' },
      { label: 'Woofer', value: '130 mm paper cone' },
      { label: 'Sensitivity', value: '86 dB / 2.83 V / 1 m' },
      { label: 'Recommended power', value: '30 – 120 W' },
    ],
    weightGrams: 12400,
    warrantyMonths: 60,
    ratingDistribution: [1, 1, 6, 22, 58],
    createdAt: '2024-06-14T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0012',
    slug: 'kestrel-nomad-portable-speaker',
    name: 'Kestrel Nomad Portable Speaker',
    brandId: 'brd-kestrel',
    categoryId: 'cat-speakers',
    sku: 'KES-NMD-PS',
    summary: 'Bluetooth speaker with a 24-hour battery and a user-replaceable cell.',
    description:
      'The Nomad’s battery is behind four screws and sold as a spare, which is rare in this category. Pairs two units into a stereo pair, and doubles as a USB-C power bank for a phone.',
    priceMinor: 12900,
    lifecycle: 'active',
    tags: ['wireless', 'portable', 'ip67', 'replaceable-battery'],
    specifications: [
      { label: 'Battery life', value: '24 hours at half volume' },
      { label: 'Water resistance', value: 'IP67' },
      { label: 'Pairing', value: 'Stereo pair from two units' },
      { label: 'Power out', value: '7.5 W USB-C' },
    ],
    weightGrams: 690,
    warrantyMonths: 24,
    ratingDistribution: [5, 8, 22, 78, 149],
    createdAt: '2025-07-02T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0013',
    slug: 'aurelia-alcove-mini',
    name: 'Aurelia Alcove Mini',
    brandId: 'brd-aurelia',
    categoryId: 'cat-speakers',
    sku: 'AUR-ALC-MN',
    summary: 'Smaller Alcove pair for desks and narrow shelves.',
    description:
      'A scaled-down Alcove with a 100 mm woofer, intended for desktop distances of under a metre. Same magnetic grilles and replaceable drivers as the larger pair.',
    priceMinor: 27900,
    lifecycle: 'active',
    tags: ['passive', 'bookshelf', 'desktop', 'pair'],
    specifications: [
      { label: 'Configuration', value: '2-way sealed' },
      { label: 'Woofer', value: '100 mm paper cone' },
      { label: 'Sensitivity', value: '84 dB / 2.83 V / 1 m' },
    ],
    weightGrams: 7800,
    warrantyMonths: 60,
    ratingDistribution: [0, 2, 5, 18, 31],
    createdAt: '2025-01-19T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0014',
    slug: 'kestrel-nomad-mini',
    name: 'Kestrel Nomad Mini',
    brandId: 'brd-kestrel',
    categoryId: 'cat-speakers',
    sku: 'KES-NMD-MN',
    summary: 'Pocket-sized Bluetooth speaker with a carabiner loop.',
    description:
      'Small enough to clip to a rucksack strap, with a 12-hour battery. Mono only, and honest about it.',
    priceMinor: 6900,
    lifecycle: 'active',
    tags: ['wireless', 'portable', 'ip67', 'compact'],
    specifications: [
      { label: 'Battery life', value: '12 hours' },
      { label: 'Water resistance', value: 'IP67' },
      { label: 'Output', value: 'Mono, 8 W' },
    ],
    weightGrams: 285,
    warrantyMonths: 12,
    ratingDistribution: [7, 11, 29, 64, 71],
    createdAt: '2026-02-05T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Laptops ====================
  {
    id: 'prd-0015',
    slug: 'vantage-meridian-14',
    name: 'Vantage Meridian 14',
    brandId: 'brd-vantage',
    categoryId: 'cat-laptops',
    sku: 'VAN-MER-14',
    summary: '14-inch laptop with socketed memory and a replaceable battery.',
    description:
      'The Meridian is Vantage’s argument that a thin laptop can still be opened. Memory and storage are socketed, the battery comes out with a single connector, and a service manual ships in the box. Weighs 1.24 kg with the 61 Wh cell.',
    priceMinor: 129900,
    lifecycle: 'active',
    tags: ['laptop', 'repairable', 'usb-c', '14-inch'],
    specifications: [
      { label: 'Display', value: '14.0 in, 2880 × 1800, 120 Hz' },
      { label: 'Memory', value: '16 GB DDR5, 2 × SO-DIMM' },
      { label: 'Storage', value: '512 GB NVMe, M.2 2280' },
      { label: 'Battery', value: '61 Wh, replaceable' },
      { label: 'Ports', value: '2 × USB-C, USB-A, HDMI, SD' },
    ],
    weightGrams: 1240,
    warrantyMonths: 24,
    ratingDistribution: [3, 4, 15, 52, 118],
    createdAt: '2025-10-15T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0016',
    slug: 'vantage-meridian-16-pro',
    name: 'Vantage Meridian 16 Pro',
    brandId: 'brd-vantage',
    categoryId: 'cat-laptops',
    sku: 'VAN-MER-16P',
    summary: '16-inch machine with a discrete GPU and 32 GB of socketed memory.',
    description:
      'A larger Meridian with a discrete GPU and a 99 Wh battery, which is the legal ceiling for cabin baggage. Two M.2 slots and four SO-DIMM slots make it unusually expandable for the size.',
    priceMinor: 214900,
    lifecycle: 'active',
    tags: ['laptop', 'repairable', 'discrete-gpu', '16-inch'],
    specifications: [
      { label: 'Display', value: '16.0 in, 3200 × 2000, 165 Hz' },
      { label: 'Memory', value: '32 GB DDR5, 4 × SO-DIMM' },
      { label: 'Storage', value: '1 TB NVMe, 2 × M.2' },
      { label: 'Battery', value: '99 Wh, replaceable' },
    ],
    weightGrams: 1980,
    warrantyMonths: 36,
    ratingDistribution: [2, 3, 9, 31, 74],
    createdAt: '2026-01-28T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0017',
    slug: 'vantage-field-13',
    name: 'Vantage Field 13',
    brandId: 'brd-vantage',
    categoryId: 'cat-laptops',
    sku: 'VAN-FLD-13',
    summary: 'Lightweight 13-inch laptop built for travel, 1.02 kg.',
    description:
      'Vantage’s smallest machine, aimed at people who carry a laptop every day and rarely dock it. Memory is soldered here, which is the compromise that got it under 1.1 kg — Vantage documents that trade-off in the spec sheet rather than hiding it.',
    priceMinor: 89900,
    compareAtMinor: 99900,
    lifecycle: 'active',
    tags: ['laptop', 'ultralight', '13-inch', 'travel'],
    specifications: [
      { label: 'Display', value: '13.3 in, 2560 × 1600, 60 Hz' },
      { label: 'Memory', value: '16 GB LPDDR5, soldered' },
      { label: 'Storage', value: '512 GB NVMe, M.2 2230' },
      { label: 'Battery', value: '54 Wh' },
    ],
    weightGrams: 1020,
    warrantyMonths: 24,
    ratingDistribution: [5, 8, 24, 61, 82],
    createdAt: '2025-03-20T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0018',
    slug: 'vantage-studio-16-workstation',
    name: 'Vantage Studio 16 Workstation',
    brandId: 'brd-vantage',
    categoryId: 'cat-laptops',
    sku: 'VAN-STU-16',
    summary: 'Colour-calibrated 16-inch workstation shipped with a measurement report.',
    description:
      'Aimed at colour work, with each panel individually profiled and the report included on paper. Heavy at 2.4 kg and loud under sustained load, which Vantage states plainly.',
    priceMinor: 289900,
    lifecycle: 'preorder',
    tags: ['laptop', 'workstation', 'colour-calibrated', '16-inch'],
    specifications: [
      { label: 'Display', value: '16.0 in, 3840 × 2400, 100% DCI-P3' },
      { label: 'Colour accuracy', value: 'Delta E < 1, per-unit report' },
      { label: 'Memory', value: '64 GB DDR5, 4 × SO-DIMM' },
      { label: 'Storage', value: '2 TB NVMe, 2 × M.2' },
    ],
    weightGrams: 2410,
    warrantyMonths: 36,
    ratingDistribution: [0, 0, 0, 0, 0],
    createdAt: '2026-07-30T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Monitors ====================
  {
    id: 'prd-0019',
    slug: 'vantage-clarity-27-4k',
    name: 'Vantage Clarity 27 4K',
    brandId: 'brd-vantage',
    categoryId: 'cat-monitors',
    sku: 'VAN-CLR-27',
    summary: '27-inch 4K display with 90 W USB-C power delivery.',
    description:
      'A matte 4K panel that drives and charges a laptop over one cable. The stand adjusts for height, tilt and rotation, and comes off for a VESA arm without tools.',
    priceMinor: 64900,
    lifecycle: 'active',
    tags: ['monitor', '4k', 'usb-c', 'vesa'],
    specifications: [
      { label: 'Panel', value: '27 in IPS, 3840 × 2160, 60 Hz' },
      { label: 'Colour', value: '98% sRGB, factory calibrated' },
      { label: 'Power delivery', value: '90 W USB-C' },
      { label: 'Stand', value: 'Height, tilt, swivel, pivot' },
    ],
    weightGrams: 6200,
    warrantyMonths: 36,
    ratingDistribution: [4, 6, 19, 68, 131],
    createdAt: '2025-08-12T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0020',
    slug: 'vantage-clarity-32-reference',
    name: 'Vantage Clarity 32 Reference',
    brandId: 'brd-vantage',
    categoryId: 'cat-monitors',
    sku: 'VAN-CLR-32R',
    summary: '32-inch reference monitor with a hardware calibration LUT.',
    description:
      'Holds calibration in a hardware lookup table rather than the graphics driver, so profiles survive an operating system reinstall. Includes a shading hood.',
    priceMinor: 119900,
    lifecycle: 'active',
    tags: ['monitor', '4k', 'colour-calibrated', 'reference'],
    specifications: [
      { label: 'Panel', value: '32 in IPS Black, 3840 × 2160' },
      { label: 'Colour', value: '99% Adobe RGB, 98% DCI-P3' },
      { label: 'Calibration', value: '16-bit hardware LUT' },
      { label: 'Included', value: 'Shading hood, calibration report' },
    ],
    weightGrams: 9700,
    warrantyMonths: 36,
    ratingDistribution: [1, 2, 6, 21, 49],
    createdAt: '2024-11-06T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0021',
    slug: 'vantage-clarity-24',
    name: 'Vantage Clarity 24',
    brandId: 'brd-vantage',
    categoryId: 'cat-monitors',
    sku: 'VAN-CLR-24',
    summary: 'Compact 24-inch 1440p monitor for smaller desks.',
    description:
      'A 1440p panel at 24 inches, which is a denser pixel pitch than most displays this size. Same tool-free stand as the rest of the Clarity line.',
    priceMinor: 32900,
    lifecycle: 'active',
    tags: ['monitor', '1440p', 'usb-c', 'compact'],
    specifications: [
      { label: 'Panel', value: '24 in IPS, 2560 × 1440, 75 Hz' },
      { label: 'Colour', value: '95% sRGB' },
      { label: 'Power delivery', value: '65 W USB-C' },
    ],
    weightGrams: 4300,
    warrantyMonths: 36,
    ratingDistribution: [6, 9, 31, 84, 96],
    createdAt: '2025-05-14T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0022',
    slug: 'vantage-curve-34-ultrawide',
    name: 'Vantage Curve 34 Ultrawide',
    brandId: 'brd-vantage',
    categoryId: 'cat-monitors',
    sku: 'VAN-CRV-34',
    summary: '34-inch curved ultrawide with a built-in KVM switch.',
    description:
      'A 21:9 panel with a KVM switch, so one keyboard and mouse can drive two machines from the display itself. The curve is a gentle 1800R rather than an aggressive one.',
    priceMinor: 84900,
    compareAtMinor: 94900,
    lifecycle: 'active',
    tags: ['monitor', 'ultrawide', 'kvm', 'curved'],
    specifications: [
      { label: 'Panel', value: '34 in VA, 3440 × 1440, 144 Hz' },
      { label: 'Curvature', value: '1800R' },
      { label: 'KVM', value: 'Two-host, USB-C and USB-B' },
    ],
    weightGrams: 8100,
    warrantyMonths: 36,
    ratingDistribution: [8, 11, 26, 59, 88],
    createdAt: '2025-12-03T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Keyboards & mice ====================
  {
    id: 'prd-0023',
    slug: 'ferrite-type-65',
    name: 'Ferrite Type 65',
    brandId: 'brd-ferrite',
    categoryId: 'cat-input',
    sku: 'FER-T65',
    summary: '65% mechanical keyboard with hot-swap sockets.',
    description:
      'A compact 65% layout that keeps the arrow keys. Switches are hot-swappable without soldering, and Ferrite sells the switches, keycaps, plate and case as separate parts.',
    priceMinor: 15900,
    lifecycle: 'active',
    tags: ['keyboard', 'mechanical', 'hot-swap', '65-percent'],
    specifications: [
      { label: 'Layout', value: '65%, 68 keys' },
      { label: 'Switches', value: 'Hot-swap, 5-pin MX' },
      { label: 'Connection', value: 'USB-C, detachable' },
      { label: 'Keycaps', value: 'PBT double-shot' },
    ],
    weightGrams: 780,
    warrantyMonths: 24,
    ratingDistribution: [3, 5, 17, 62, 178],
    createdAt: '2025-06-25T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0024',
    slug: 'ferrite-type-87-tactile',
    name: 'Ferrite Type 87 Tactile',
    brandId: 'brd-ferrite',
    categoryId: 'cat-input',
    sku: 'FER-T87-TAC',
    summary: 'Tenkeyless keyboard fitted with tactile switches.',
    description:
      'The tenkeyless Ferrite, shipped with tactile switches rather than linears. Gasket mounted, which softens the typing feel noticeably compared with the Type 65.',
    priceMinor: 18900,
    lifecycle: 'active',
    tags: ['keyboard', 'mechanical', 'tenkeyless', 'hot-swap'],
    specifications: [
      { label: 'Layout', value: 'Tenkeyless, 87 keys' },
      { label: 'Switches', value: 'Tactile, hot-swap' },
      { label: 'Mounting', value: 'Gasket' },
      { label: 'Connection', value: 'USB-C, detachable' },
    ],
    weightGrams: 1010,
    warrantyMonths: 24,
    ratingDistribution: [2, 4, 12, 44, 101],
    createdAt: '2025-09-18T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0025',
    slug: 'ferrite-type-104-full',
    name: 'Ferrite Type 104 Full',
    brandId: 'brd-ferrite',
    categoryId: 'cat-input',
    sku: 'FER-T104',
    summary: 'Full-size keyboard with a number pad and a rotary encoder.',
    description:
      'The full-size layout, with a rotary encoder in the top right corner mapped to volume by default. Heavier than it needs to be, deliberately.',
    priceMinor: 19900,
    lifecycle: 'active',
    tags: ['keyboard', 'mechanical', 'full-size', 'rotary-encoder'],
    specifications: [
      { label: 'Layout', value: 'Full size, 104 keys' },
      { label: 'Switches', value: 'Hot-swap, 5-pin MX' },
      { label: 'Extras', value: 'Rotary encoder' },
    ],
    weightGrams: 1340,
    warrantyMonths: 24,
    ratingDistribution: [4, 6, 18, 41, 63],
    createdAt: '2025-02-04T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0026',
    slug: 'ferrite-glide-wireless-mouse',
    name: 'Ferrite Glide Wireless Mouse',
    brandId: 'brd-ferrite',
    categoryId: 'cat-input',
    sku: 'FER-GLD-WM',
    summary: 'Lightweight wireless mouse, 58 g, with replaceable feet.',
    description:
      'A 58 g shell without the honeycomb cutouts that usually come with that weight. Feet and the USB-C port module are both replaceable.',
    priceMinor: 8900,
    lifecycle: 'active',
    tags: ['mouse', 'wireless', 'lightweight', 'replaceable-parts'],
    specifications: [
      { label: 'Weight', value: '58 g' },
      { label: 'Sensor', value: '26,000 DPI optical' },
      { label: 'Battery life', value: '90 hours' },
      { label: 'Polling', value: '1000 Hz wireless' },
    ],
    weightGrams: 58,
    warrantyMonths: 24,
    ratingDistribution: [7, 9, 24, 71, 134],
    createdAt: '2025-10-09T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0027',
    slug: 'ferrite-deskmat-xl',
    name: 'Ferrite Deskmat XL',
    brandId: 'brd-ferrite',
    categoryId: 'cat-input',
    sku: 'FER-DSK-XL',
    summary: 'Stitched desk mat, 900 × 400 mm, machine washable.',
    description:
      'A large cloth mat with stitched edges that do not fray. Washable at 30 °C, which matters more than any other specification for something that lives under your hands.',
    priceMinor: 3900,
    lifecycle: 'active',
    tags: ['desk-mat', 'accessory', 'washable'],
    specifications: [
      { label: 'Size', value: '900 × 400 × 4 mm' },
      { label: 'Surface', value: 'Woven polyester' },
      { label: 'Base', value: 'Natural rubber' },
    ],
    weightGrams: 620,
    warrantyMonths: 12,
    ratingDistribution: [2, 3, 11, 38, 74],
    createdAt: '2024-09-27T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Cameras ====================
  {
    id: 'prd-0028',
    slug: 'northwind-arc-r6',
    name: 'Northwind Arc R6',
    brandId: 'brd-northwind',
    categoryId: 'cat-cameras',
    sku: 'NOR-ARC-R6',
    summary: 'Full-frame mirrorless body with in-body stabilisation.',
    description:
      'A 33 megapixel full-frame body with five-axis stabilisation and weather sealing. Uses the Northwind mount, unchanged since 1991, so old glass mounts directly without an adapter.',
    priceMinor: 189900,
    lifecycle: 'active',
    tags: ['camera', 'full-frame', 'mirrorless', 'weather-sealed'],
    specifications: [
      { label: 'Sensor', value: '33 MP full-frame CMOS' },
      { label: 'Stabilisation', value: '5-axis, 7 stops' },
      { label: 'Video', value: '4K 60p, 10-bit internal' },
      { label: 'Cards', value: '2 × SD UHS-II' },
    ],
    weightGrams: 658,
    warrantyMonths: 24,
    ratingDistribution: [2, 3, 8, 29, 87],
    createdAt: '2025-04-22T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0029',
    slug: 'northwind-arc-r3',
    name: 'Northwind Arc R3',
    brandId: 'brd-northwind',
    categoryId: 'cat-cameras',
    sku: 'NOR-ARC-R3',
    summary: 'APS-C mirrorless body, lighter and cheaper than the R6.',
    description:
      'The APS-C entry into the Northwind mount. Smaller sensor, same lens compatibility, and around 200 g lighter than the R6 body.',
    priceMinor: 119900,
    lifecycle: 'active',
    tags: ['camera', 'aps-c', 'mirrorless'],
    specifications: [
      { label: 'Sensor', value: '26 MP APS-C CMOS' },
      { label: 'Stabilisation', value: '5-axis, 5.5 stops' },
      { label: 'Video', value: '4K 30p' },
      { label: 'Cards', value: '1 × SD UHS-II' },
    ],
    weightGrams: 462,
    warrantyMonths: 24,
    ratingDistribution: [3, 5, 14, 41, 66],
    createdAt: '2024-10-11T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0030',
    slug: 'northwind-pocket-28',
    name: 'Northwind Pocket 28',
    brandId: 'brd-northwind',
    categoryId: 'cat-cameras',
    sku: 'NOR-PKT-28',
    summary: 'Fixed 28 mm compact camera with a one-inch sensor.',
    description:
      'A compact with a fixed 28 mm equivalent lens and no zoom, which keeps it genuinely pocketable. Manual aperture ring, and a physical switch for stills and video.',
    priceMinor: 74900,
    lifecycle: 'active',
    tags: ['camera', 'compact', 'fixed-lens', 'travel'],
    specifications: [
      { label: 'Sensor', value: '20 MP 1-inch' },
      { label: 'Lens', value: '28 mm equivalent, f/1.7' },
      { label: 'Controls', value: 'Manual aperture ring' },
    ],
    weightGrams: 298,
    warrantyMonths: 24,
    ratingDistribution: [4, 7, 16, 38, 52],
    createdAt: '2026-03-17T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Lenses ====================
  {
    id: 'prd-0031',
    slug: 'northwind-35mm-f18-prime',
    name: 'Northwind 35mm f/1.8 Prime',
    brandId: 'brd-northwind',
    categoryId: 'cat-lenses',
    sku: 'NOR-35-18',
    summary: 'Compact 35 mm prime, weather sealed.',
    description:
      'The lens most Northwind owners buy first: 35 mm, f/1.8, and light enough to leave mounted. Sealed at the mount and rated for the same conditions as the R6 body.',
    priceMinor: 54900,
    lifecycle: 'active',
    tags: ['lens', 'prime', '35mm', 'weather-sealed'],
    specifications: [
      { label: 'Focal length', value: '35 mm' },
      { label: 'Maximum aperture', value: 'f/1.8' },
      { label: 'Filter thread', value: '55 mm' },
      { label: 'Minimum focus', value: '0.28 m' },
    ],
    weightGrams: 281,
    warrantyMonths: 36,
    ratingDistribution: [1, 2, 7, 26, 78],
    createdAt: '2024-05-08T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0032',
    slug: 'northwind-85mm-f14-portrait',
    name: 'Northwind 85mm f/1.4 Portrait',
    brandId: 'brd-northwind',
    categoryId: 'cat-lenses',
    sku: 'NOR-85-14',
    summary: 'Fast 85 mm portrait lens with an eleven-blade aperture.',
    description:
      'An eleven-blade aperture keeps out-of-focus highlights round when stopped down, which is the whole reason to buy an 85 mm at this price. Heavy at 985 g.',
    priceMinor: 104900,
    lifecycle: 'active',
    tags: ['lens', 'prime', '85mm', 'portrait'],
    specifications: [
      { label: 'Focal length', value: '85 mm' },
      { label: 'Maximum aperture', value: 'f/1.4' },
      { label: 'Aperture blades', value: '11, rounded' },
      { label: 'Filter thread', value: '77 mm' },
    ],
    weightGrams: 985,
    warrantyMonths: 36,
    ratingDistribution: [0, 1, 4, 14, 47],
    createdAt: '2025-01-30T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0033',
    slug: 'northwind-16-50mm-f4-zoom',
    name: 'Northwind 16-50mm f/4 Zoom',
    brandId: 'brd-northwind',
    categoryId: 'cat-lenses',
    sku: 'NOR-1650-4',
    summary: 'Constant f/4 standard zoom for APS-C bodies.',
    description:
      'A constant aperture standard zoom for the Arc R3, covering 24–75 mm equivalent. Internal zoom, so the barrel does not extend and the balance stays constant.',
    priceMinor: 69900,
    compareAtMinor: 79900,
    lifecycle: 'active',
    tags: ['lens', 'zoom', 'aps-c', 'weather-sealed'],
    specifications: [
      { label: 'Focal length', value: '16 – 50 mm' },
      { label: 'Maximum aperture', value: 'f/4 constant' },
      { label: 'Zoom', value: 'Internal' },
      { label: 'Filter thread', value: '67 mm' },
    ],
    weightGrams: 465,
    warrantyMonths: 36,
    ratingDistribution: [2, 4, 11, 32, 41],
    createdAt: '2025-07-16T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Wearables ====================
  {
    id: 'prd-0034',
    slug: 'kestrel-pulse-3',
    name: 'Kestrel Pulse 3',
    brandId: 'brd-kestrel',
    categoryId: 'cat-wearables',
    sku: 'KES-PLS-3',
    summary: 'Smartwatch with a 14-day battery and offline maps.',
    description:
      'Runs about fourteen days between charges by not trying to be a phone. Maps are stored on the watch, so navigation works with the phone left at home.',
    priceMinor: 24900,
    lifecycle: 'active',
    tags: ['smartwatch', 'gps', 'long-battery', 'offline-maps'],
    specifications: [
      { label: 'Battery life', value: '14 days typical' },
      { label: 'Display', value: '1.3 in AMOLED, always-on' },
      { label: 'Water resistance', value: '10 ATM' },
      { label: 'Sensors', value: 'GPS, heart rate, SpO2, barometer' },
    ],
    weightGrams: 43,
    warrantyMonths: 24,
    ratingDistribution: [9, 13, 38, 104, 187],
    createdAt: '2025-11-05T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0035',
    slug: 'kestrel-pulse-lite',
    name: 'Kestrel Pulse Lite',
    brandId: 'brd-kestrel',
    categoryId: 'cat-wearables',
    sku: 'KES-PLS-LT',
    summary: 'Slimmer Pulse without onboard GPS.',
    description:
      'Drops the GPS chip and the barometer, borrowing location from a paired phone instead. Battery life goes up to about eighteen days as a result.',
    priceMinor: 12900,
    lifecycle: 'active',
    tags: ['smartwatch', 'long-battery', 'slim'],
    specifications: [
      { label: 'Battery life', value: '18 days typical' },
      { label: 'Display', value: '1.1 in AMOLED' },
      { label: 'Water resistance', value: '5 ATM' },
    ],
    weightGrams: 31,
    warrantyMonths: 24,
    ratingDistribution: [11, 17, 44, 92, 88],
    createdAt: '2025-03-05T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0036',
    slug: 'kestrel-trail-gps-watch',
    name: 'Kestrel Trail GPS Watch',
    brandId: 'brd-kestrel',
    categoryId: 'cat-wearables',
    sku: 'KES-TRL-GPS',
    summary: 'Rugged GPS watch with multi-band positioning and a sapphire lens.',
    description:
      'Built for long days outdoors: multi-band GPS, a sapphire crystal, and a titanium bezel. Battery runs about 40 hours with the GPS recording continuously.',
    priceMinor: 37900,
    lifecycle: 'active',
    tags: ['smartwatch', 'gps', 'rugged', 'sapphire'],
    specifications: [
      { label: 'Battery life', value: '40 hours GPS, 21 days watch' },
      { label: 'Positioning', value: 'Multi-band GNSS' },
      { label: 'Lens', value: 'Sapphire crystal' },
      { label: 'Case', value: 'Titanium bezel' },
    ],
    weightGrams: 58,
    warrantyMonths: 24,
    ratingDistribution: [3, 5, 12, 44, 96],
    createdAt: '2026-04-14T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0037',
    slug: 'kestrel-band-sleep-tracker',
    name: 'Kestrel Band Sleep Tracker',
    brandId: 'brd-kestrel',
    categoryId: 'cat-wearables',
    sku: 'KES-BND-ST',
    summary: 'Screenless band that tracks sleep and recovery.',
    description:
      'Has no screen at all, which is the point — it is meant to be worn overnight without a display waking you. Charges weekly on a magnetic puck.',
    priceMinor: 7900,
    lifecycle: 'active',
    tags: ['tracker', 'sleep', 'screenless'],
    specifications: [
      { label: 'Battery life', value: '7 days' },
      { label: 'Sensors', value: 'Heart rate, SpO2, skin temperature' },
      { label: 'Water resistance', value: '5 ATM' },
    ],
    weightGrams: 22,
    warrantyMonths: 12,
    ratingDistribution: [18, 24, 51, 78, 61],
    createdAt: '2025-08-21T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Kitchen ====================
  {
    id: 'prd-0038',
    slug: 'solace-ember-pour-over-kettle',
    name: 'Solace Ember Pour-Over Kettle',
    brandId: 'brd-solace',
    categoryId: 'cat-kitchen',
    sku: 'SOL-EMB-PK',
    summary: 'Variable temperature gooseneck kettle, 0.9 litre.',
    description:
      'A gooseneck kettle with temperature set in one degree steps and a thirty minute hold. Stainless steel throughout, including the interior of the spout, with no plastic in the water path.',
    priceMinor: 11900,
    lifecycle: 'active',
    tags: ['kettle', 'coffee', 'stainless-steel', 'variable-temperature'],
    specifications: [
      { label: 'Capacity', value: '0.9 L' },
      { label: 'Temperature range', value: '40 – 100 °C, 1 °C steps' },
      { label: 'Hold', value: '30 minutes' },
      { label: 'Water path', value: 'Stainless steel, no plastic' },
    ],
    weightGrams: 1180,
    warrantyMonths: 24,
    ratingDistribution: [5, 8, 21, 74, 162],
    createdAt: '2025-01-14T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0039',
    slug: 'solace-grind-40-coffee-grinder',
    name: 'Solace Grind 40 Coffee Grinder',
    brandId: 'brd-solace',
    categoryId: 'cat-kitchen',
    sku: 'SOL-GRD-40',
    summary: 'Conical burr grinder with 40 stepped settings.',
    description:
      'Forty stepped settings from espresso to French press, with 40 mm hardened steel burrs. The burrs come out for cleaning without tools and are sold as spares.',
    priceMinor: 18900,
    compareAtMinor: 21900,
    lifecycle: 'active',
    tags: ['grinder', 'coffee', 'burr', 'replaceable-parts'],
    specifications: [
      { label: 'Burrs', value: '40 mm conical, hardened steel' },
      { label: 'Settings', value: '40 stepped' },
      { label: 'Hopper', value: '250 g' },
    ],
    weightGrams: 2650,
    warrantyMonths: 24,
    ratingDistribution: [7, 11, 26, 62, 104],
    createdAt: '2024-12-02T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0040',
    slug: 'solace-cast-iron-skillet-26cm',
    name: 'Solace Cast Iron Skillet 26cm',
    brandId: 'brd-solace',
    categoryId: 'cat-kitchen',
    sku: 'SOL-CIS-26',
    summary: 'Pre-seasoned cast iron skillet with a machined cooking surface.',
    description:
      'The cooking face is machined smooth before seasoning, which most cast iron is not. Oven safe to any temperature, and heavy enough at 2.4 kg to be worth mentioning.',
    priceMinor: 6900,
    lifecycle: 'active',
    tags: ['cookware', 'cast-iron', 'oven-safe'],
    specifications: [
      { label: 'Diameter', value: '26 cm' },
      { label: 'Surface', value: 'Machined, pre-seasoned' },
      { label: 'Oven safe', value: 'Unlimited' },
    ],
    weightGrams: 2410,
    warrantyMonths: 300,
    ratingDistribution: [2, 4, 9, 31, 88],
    createdAt: '2024-04-18T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0041',
    slug: 'solace-vessel-vacuum-flask-750ml',
    name: 'Solace Vessel Vacuum Flask 750ml',
    brandId: 'brd-solace',
    categoryId: 'cat-kitchen',
    sku: 'SOL-VSL-750',
    summary: 'Double-walled flask with a fully dishwasher-safe lid.',
    description:
      'The lid comes apart into three pieces with no glued gaskets, so it can actually be cleaned. Holds heat for around eighteen hours.',
    priceMinor: 3900,
    lifecycle: 'active',
    tags: ['flask', 'stainless-steel', 'dishwasher-safe'],
    specifications: [
      { label: 'Capacity', value: '750 ml' },
      { label: 'Heat retention', value: '18 hours' },
      { label: 'Lid', value: '3-part, dishwasher safe' },
    ],
    weightGrams: 420,
    warrantyMonths: 60,
    ratingDistribution: [4, 6, 18, 54, 71],
    createdAt: '2025-09-29T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Lighting ====================
  {
    id: 'prd-0042',
    slug: 'lumina-arc-desk-lamp',
    name: 'Lumina Arc Desk Lamp',
    brandId: 'brd-lumina',
    categoryId: 'cat-lighting',
    sku: 'LUM-ARC-DL',
    summary: 'Asymmetric desk lamp with adjustable colour temperature.',
    description:
      'Throws light forward across a desk rather than down in a pool, which keeps it off a monitor. Colour temperature adjusts from 2700 K to 5000 K, and it remembers the last setting without an app.',
    priceMinor: 14900,
    lifecycle: 'active',
    tags: ['lamp', 'desk', 'adjustable-white', 'local-control'],
    specifications: [
      { label: 'Output', value: '1100 lm' },
      { label: 'Colour temperature', value: '2700 – 5000 K' },
      { label: 'CRI', value: '95' },
      { label: 'Control', value: 'On-device, no account required' },
    ],
    weightGrams: 1650,
    warrantyMonths: 36,
    ratingDistribution: [3, 5, 14, 48, 92],
    createdAt: '2025-10-28T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0043',
    slug: 'lumina-glow-a19-smart-bulb-4-pack',
    name: 'Lumina Glow A19 Smart Bulb (4-pack)',
    brandId: 'brd-lumina',
    categoryId: 'cat-lighting',
    sku: 'LUM-GLW-A19-4',
    summary: 'Four colour smart bulbs that run without a cloud account.',
    description:
      'Firmware is local-first: schedules and scenes run on the bulb, so they keep working if the internet or the vendor goes away. Works over Matter with any hub.',
    priceMinor: 5900,
    lifecycle: 'active',
    tags: ['smart-bulb', 'matter', 'local-control', 'multipack'],
    specifications: [
      { label: 'Pack size', value: '4 bulbs' },
      { label: 'Output', value: '806 lm each' },
      { label: 'Colour', value: '16 M colours plus 2200 – 6500 K' },
      { label: 'Protocol', value: 'Matter over Thread' },
    ],
    weightGrams: 340,
    warrantyMonths: 24,
    ratingDistribution: [12, 16, 39, 88, 134],
    createdAt: '2025-05-06T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0044',
    slug: 'lumina-panel-wall-light',
    name: 'Lumina Panel Wall Light',
    brandId: 'brd-lumina',
    categoryId: 'cat-lighting',
    sku: 'LUM-PNL-WL',
    summary: 'Flat wall panel providing indirect, diffuse light.',
    description:
      'A 40 cm square panel that washes a wall rather than lighting a room directly. Dimmable to one percent, which most panels are not.',
    priceMinor: 19900,
    lifecycle: 'active',
    tags: ['wall-light', 'dimmable', 'indirect'],
    specifications: [
      { label: 'Size', value: '400 × 400 × 22 mm' },
      { label: 'Output', value: '1800 lm' },
      { label: 'Dimming', value: '1 – 100%' },
    ],
    weightGrams: 2100,
    warrantyMonths: 36,
    ratingDistribution: [1, 2, 6, 17, 24],
    createdAt: '2026-05-19T09:00:00.000Z',
    isFeatured: false,
  },

  // ==================== Accessories ====================
  {
    id: 'prd-0045',
    slug: 'marlow-commuter-backpack-22l',
    name: 'Marlow Commuter Backpack 22L',
    brandId: 'brd-marlow',
    categoryId: 'cat-accessories',
    sku: 'MAR-CMB-22',
    summary: 'Recycled-fabric backpack with a 16-inch laptop compartment.',
    description:
      'A 22 litre commuter pack made from recycled nylon, with a padded compartment that takes a 16 inch laptop. Marlow will repair it for ten years, zips included.',
    priceMinor: 12900,
    lifecycle: 'active',
    tags: ['backpack', 'recycled', 'laptop', 'repairable'],
    specifications: [
      { label: 'Capacity', value: '22 L' },
      { label: 'Laptop', value: 'Up to 16 in' },
      { label: 'Fabric', value: 'Recycled 420D nylon' },
      { label: 'Repair', value: '10 years, including zips' },
    ],
    weightGrams: 940,
    warrantyMonths: 120,
    ratingDistribution: [6, 9, 24, 81, 158],
    createdAt: '2025-06-03T09:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prd-0046',
    slug: 'marlow-sleeve-14',
    name: 'Marlow Sleeve 14"',
    brandId: 'brd-marlow',
    categoryId: 'cat-accessories',
    sku: 'MAR-SLV-14',
    summary: 'Felt laptop sleeve with a magnetic closure.',
    description:
      'Wool felt with a magnetic flap rather than a zip, so nothing metal can meet a laptop lid. Fits 14 inch machines including the Meridian 14.',
    priceMinor: 4900,
    lifecycle: 'active',
    tags: ['sleeve', 'laptop', 'wool-felt'],
    specifications: [
      { label: 'Fits', value: '14 in laptops' },
      { label: 'Material', value: '3 mm wool felt' },
      { label: 'Closure', value: 'Magnetic flap' },
    ],
    weightGrams: 210,
    warrantyMonths: 24,
    ratingDistribution: [3, 4, 12, 34, 47],
    createdAt: '2024-07-25T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0047',
    slug: 'marlow-braided-usb-c-cable-2m',
    name: 'Marlow Braided USB-C Cable 2m',
    brandId: 'brd-marlow',
    categoryId: 'cat-accessories',
    sku: 'MAR-USBC-2M',
    summary: '240 W USB-C cable with braided sleeving and 40 Gbps data.',
    description:
      'Rated for 240 W charging and 40 Gbps of data, which is the full USB4 specification rather than the charging-only cable this usually turns out to be. Braided sleeving and moulded strain relief at both ends.',
    priceMinor: 1900,
    lifecycle: 'active',
    tags: ['cable', 'usb-c', 'usb4', '240w'],
    specifications: [
      { label: 'Length', value: '2 m' },
      { label: 'Power', value: '240 W, 48 V 5 A' },
      { label: 'Data', value: '40 Gbps USB4' },
      { label: 'Video', value: 'DisplayPort Alt Mode' },
    ],
    weightGrams: 92,
    warrantyMonths: 24,
    ratingDistribution: [8, 11, 27, 68, 121],
    createdAt: '2025-04-01T09:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'prd-0048',
    slug: 'marlow-travel-charger-65w',
    name: 'Marlow Travel Charger 65W',
    brandId: 'brd-marlow',
    categoryId: 'cat-accessories',
    sku: 'MAR-CHG-65',
    summary: 'Three-port GaN charger with interchangeable plugs.',
    description:
      'A 65 W gallium nitride charger with two USB-C ports and one USB-A, plus swappable plugs for UK, EU and US sockets in the box. Small enough to leave in a bag permanently.',
    priceMinor: 5900,
    lifecycle: 'active',
    tags: ['charger', 'gan', 'travel', 'usb-c'],
    specifications: [
      { label: 'Total output', value: '65 W' },
      { label: 'Ports', value: '2 × USB-C, 1 × USB-A' },
      { label: 'Plugs included', value: 'UK, EU, US' },
    ],
    weightGrams: 148,
    warrantyMonths: 24,
    ratingDistribution: [5, 7, 19, 62, 97],
    createdAt: '2026-06-08T09:00:00.000Z',
    isFeatured: false,
  },
];
