import type { Review } from '@core/models';

/**
 * Review seed records.
 *
 * A representative sample rather than a full corpus. Products carry their own rating
 * histogram (see `products.mock.ts`), which is what the catalogue displays; these are
 * the readable reviews behind a subset of them.
 *
 * Deliberately includes critical and mid-range reviews. A fixture where everything is
 * five stars hides every layout problem that real review text causes — long titles,
 * unverified purchases, and the awkward one-star case.
 */
export const REVIEW_SEEDS: readonly Review[] = [
  // ---------- Aurelia Studio One Open-Back ----------
  {
    id: 'rev-0001',
    productId: 'prd-0001',
    authorName: 'Marcus T.',
    verifiedPurchase: true,
    score: 5,
    title: 'Still the reference after three years',
    body: 'I mix on these daily and they have never flattered a bad recording, which is exactly what I wanted. Replaced the earpads once at around eighteen months; took two minutes and cost twelve pounds.',
    createdAt: '2026-05-14T10:22:00.000Z',
    helpfulCount: 84,
  },
  {
    id: 'rev-0002',
    productId: 'prd-0001',
    authorName: 'Elena K.',
    verifiedPurchase: true,
    score: 4,
    title: 'Superb sound, but understand what open-back means',
    body: 'Everyone in the room can hear what I am listening to, and I can hear them. That is the design, not a fault, but I would not buy these for an office. Sound quality is worth the caveat at home.',
    createdAt: '2026-03-02T18:41:00.000Z',
    helpfulCount: 122,
  },
  {
    id: 'rev-0003',
    productId: 'prd-0001',
    authorName: 'Dev P.',
    verifiedPurchase: false,
    score: 3,
    title: 'Needs an amp to come alive',
    body: 'At 250 ohms these are wasted on a laptop headphone jack. Once I added a small desktop amp they transformed. Factor that cost in before ordering.',
    createdAt: '2025-11-19T09:05:00.000Z',
    helpfulCount: 67,
  },

  // ---------- Aurelia Meridian ANC ----------
  {
    id: 'rev-0004',
    productId: 'prd-0003',
    authorName: 'Sam W.',
    verifiedPurchase: true,
    score: 5,
    title: 'Finally, cancelling that does not colour the sound',
    body: 'Most noise cancelling headphones sound hollow with the cancelling on. These barely change. Flew London to Singapore and had well over half the battery left on landing.',
    createdAt: '2026-07-28T21:14:00.000Z',
    helpfulCount: 156,
  },
  {
    id: 'rev-0005',
    productId: 'prd-0003',
    authorName: 'Rachel M.',
    verifiedPurchase: true,
    score: 4,
    title: 'Excellent, though the case is enormous',
    body: 'No complaints about the headphones themselves. The hard case is much bigger than it needs to be and does not fit in a small bag, so I leave it at home.',
    createdAt: '2026-06-11T13:38:00.000Z',
    helpfulCount: 41,
  },
  {
    id: 'rev-0006',
    productId: 'prd-0003',
    authorName: 'Anon',
    verifiedPurchase: false,
    score: 2,
    title: 'Clamping force too high for me',
    body: 'Sound is genuinely very good but after ninety minutes I get a headache from the pressure. I have a wide head and these did not loosen with wearing. Returned them.',
    createdAt: '2026-04-05T08:52:00.000Z',
    helpfulCount: 93,
  },

  // ---------- Kestrel Pip Pro ----------
  {
    id: 'rev-0007',
    productId: 'prd-0007',
    authorName: 'Yusuf A.',
    verifiedPurchase: true,
    score: 5,
    title: 'The tips actually being sold separately is the selling point',
    body: 'I lose tips constantly. Being able to buy a pack of four for six pounds instead of replacing the whole set is why I switched to these and will stay.',
    createdAt: '2026-08-02T16:20:00.000Z',
    helpfulCount: 71,
  },
  {
    id: 'rev-0008',
    productId: 'prd-0007',
    authorName: 'Chloe B.',
    verifiedPurchase: true,
    score: 5,
    title: 'Better than sets twice the price',
    body: 'Cancelling handles train noise well and the case charges on the same pad as my phone. Eight hours is accurate rather than optimistic.',
    createdAt: '2026-06-24T07:44:00.000Z',
    helpfulCount: 38,
  },
  {
    id: 'rev-0009',
    productId: 'prd-0007',
    authorName: 'Tom H.',
    verifiedPurchase: true,
    score: 3,
    title: 'Fine, but the touch controls are oversensitive',
    body: 'Adjusting them in my ear pauses the music about half the time. There is no way to turn the gestures off in the app, which is an odd omission.',
    createdAt: '2026-02-17T19:02:00.000Z',
    helpfulCount: 112,
  },

  // ---------- Vantage Meridian 14 ----------
  {
    id: 'rev-0010',
    productId: 'prd-0015',
    authorName: 'Priya R.',
    verifiedPurchase: true,
    score: 5,
    title: 'Upgraded the RAM myself in ten minutes',
    body: 'Bought the 16 GB model and put 48 GB in six months later for a fraction of the configure-to-order price. The service manual in the box tells you exactly which screws. More laptops should work like this.',
    createdAt: '2026-07-09T11:31:00.000Z',
    helpfulCount: 203,
  },
  {
    id: 'rev-0011',
    productId: 'prd-0015',
    authorName: 'Alex F.',
    verifiedPurchase: true,
    score: 4,
    title: 'Great machine, fans are audible under load',
    body: 'Silent for everything I do day to day, but compiling anything large spins the fans up noticeably. Not loud exactly, just present. Worth knowing if you work in a quiet room.',
    createdAt: '2026-05-30T14:17:00.000Z',
    helpfulCount: 58,
  },
  {
    id: 'rev-0012',
    productId: 'prd-0015',
    authorName: 'Bea N.',
    verifiedPurchase: true,
    score: 5,
    title: 'The 120 Hz screen is the surprise',
    body: 'I did not think a high refresh rate would matter on a work laptop. Scrolling code is noticeably easier on my eyes over a long day.',
    createdAt: '2026-03-21T09:48:00.000Z',
    helpfulCount: 34,
  },

  // ---------- Vantage Clarity 27 4K ----------
  {
    id: 'rev-0013',
    productId: 'prd-0019',
    authorName: 'Daniel O.',
    verifiedPurchase: true,
    score: 5,
    title: 'One cable to the laptop and that is it',
    body: 'Ninety watts is enough to charge the Meridian 16 while driving the display. Desk went from four cables to one. Stand is genuinely adjustable rather than tilt-only.',
    createdAt: '2026-06-18T15:55:00.000Z',
    helpfulCount: 97,
  },
  {
    id: 'rev-0014',
    productId: 'prd-0019',
    authorName: 'Iwona S.',
    verifiedPurchase: true,
    score: 4,
    title: 'Matte coating is the right call',
    body: 'I sit opposite a window and there is no usable reflection. Slight loss of contrast punch versus a glossy panel, which I will take every time.',
    createdAt: '2026-01-27T12:09:00.000Z',
    helpfulCount: 45,
  },
  {
    id: 'rev-0015',
    productId: 'prd-0019',
    authorName: 'Anon',
    verifiedPurchase: false,
    score: 1,
    title: 'Dead pixel out of the box',
    body: 'Arrived with a stuck red subpixel near the centre. Support replaced it without argument and the second unit is perfect, so one star is for the panel lottery rather than the company.',
    createdAt: '2025-12-14T17:23:00.000Z',
    helpfulCount: 76,
  },

  // ---------- Ferrite Type 65 ----------
  {
    id: 'rev-0016',
    productId: 'prd-0023',
    authorName: 'Reuben C.',
    verifiedPurchase: true,
    score: 5,
    title: 'Swapped the switches twice without soldering',
    body: 'Started on linears, moved to tactiles, ended on silent tactiles. Same board throughout. Being able to buy ten switches to try is far better than buying three keyboards.',
    createdAt: '2026-07-22T20:31:00.000Z',
    helpfulCount: 141,
  },
  {
    id: 'rev-0017',
    productId: 'prd-0023',
    authorName: 'Mei L.',
    verifiedPurchase: true,
    score: 5,
    title: 'Keeps the arrows, loses the waste',
    body: 'The 65% layout is the sweet spot. Full arrow cluster, no number pad I never touched. PBT caps still look new after a year.',
    createdAt: '2026-04-16T08:12:00.000Z',
    helpfulCount: 62,
  },
  {
    id: 'rev-0018',
    productId: 'prd-0023',
    authorName: 'Greg W.',
    verifiedPurchase: true,
    score: 4,
    title: 'Ping on the spacebar out of the box',
    body: 'There was a metallic ring on the spacebar until I added a strip of foam under the plate, which took five minutes. Everything else was flawless.',
    createdAt: '2026-02-08T10:47:00.000Z',
    helpfulCount: 88,
  },

  // ---------- Kestrel Pulse 3 ----------
  {
    id: 'rev-0019',
    productId: 'prd-0034',
    authorName: 'Fiona D.',
    verifiedPurchase: true,
    score: 5,
    title: 'Two weeks of battery is not marketing',
    body: 'Always-on display, notifications, an hour of GPS most days, and I still charge it on alternate Sundays. Offline maps got me back to a car park with no signal.',
    createdAt: '2026-08-05T06:39:00.000Z',
    helpfulCount: 118,
  },
  {
    id: 'rev-0020',
    productId: 'prd-0034',
    authorName: 'Owen J.',
    verifiedPurchase: true,
    score: 4,
    title: 'Hardware excellent, app is mediocre',
    body: 'The watch is superb. The companion app is slow and buries the settings I want. It works, it is just clearly the lower priority.',
    createdAt: '2026-06-02T18:26:00.000Z',
    helpfulCount: 94,
  },
  {
    id: 'rev-0021',
    productId: 'prd-0034',
    authorName: 'Anon',
    verifiedPurchase: false,
    score: 2,
    title: 'Heart rate wanders during weights',
    body: 'Accurate for running and cycling. During weight training it reads thirty beats low then spikes. Strap tension made no difference.',
    createdAt: '2026-03-11T16:04:00.000Z',
    helpfulCount: 67,
  },

  // ---------- Solace Ember Pour-Over Kettle ----------
  {
    id: 'rev-0022',
    productId: 'prd-0038',
    authorName: 'Kirsty A.',
    verifiedPurchase: true,
    score: 5,
    title: 'No plastic anywhere near the water',
    body: 'This was the only kettle I could find with a fully steel water path at a sensible price. Pour control is excellent and the thirty minute hold means I am not rushing.',
    createdAt: '2026-07-15T07:18:00.000Z',
    helpfulCount: 132,
  },
  {
    id: 'rev-0023',
    productId: 'prd-0038',
    authorName: 'Ben R.',
    verifiedPurchase: true,
    score: 4,
    title: 'Excellent kettle, base is a bit light',
    body: 'Lifting the kettle sometimes drags the base along the worktop. Minor, and everything else about it is right.',
    createdAt: '2026-05-08T06:52:00.000Z',
    helpfulCount: 29,
  },
  {
    id: 'rev-0024',
    productId: 'prd-0038',
    authorName: 'Nadia O.',
    verifiedPurchase: true,
    score: 5,
    title: 'One degree steps are worth it',
    body: 'Different beans genuinely want different temperatures and this is the first kettle that let me be precise about it. Well made.',
    createdAt: '2026-08-14T08:03:00.000Z',
    helpfulCount: 47,
  },

  // ---------- Marlow Commuter Backpack ----------
  {
    id: 'rev-0025',
    productId: 'prd-0045',
    authorName: 'Harriet V.',
    verifiedPurchase: true,
    score: 5,
    title: 'They repaired a zip free after two years',
    body: 'The main zip pull sheared. Sent it in, came back in nine days with a new zip and no charge. The ten year repair promise is real, which changes how I think about the price.',
    createdAt: '2026-06-27T13:44:00.000Z',
    helpfulCount: 187,
  },
  {
    id: 'rev-0026',
    productId: 'prd-0045',
    authorName: 'Luca B.',
    verifiedPurchase: true,
    score: 4,
    title: 'Holds a 16 inch laptop properly',
    body: 'Padding is substantial and the laptop sits against my back rather than sagging outward. Slightly short on small pockets for the size.',
    createdAt: '2026-04-30T09:21:00.000Z',
    helpfulCount: 52,
  },
  {
    id: 'rev-0027',
    productId: 'prd-0045',
    authorName: 'Anon',
    verifiedPurchase: false,
    score: 3,
    title: 'Not waterproof, despite what I assumed',
    body: 'The fabric is water resistant, not waterproof, and the zips are not sealed. Caught a downpour and the contents were damp. Marlow do state this; I did not read carefully.',
    createdAt: '2026-01-09T15:37:00.000Z',
    helpfulCount: 103,
  },

  // ---------- Northwind Arc R6 ----------
  {
    id: 'rev-0028',
    productId: 'prd-0028',
    authorName: 'Stefan M.',
    verifiedPurchase: true,
    score: 5,
    title: 'My 1998 lenses mount and work',
    body: 'Thirty years of the same mount means the lenses I inherited work with autofocus on a modern body. No adapter, no compromises. That compatibility is why I stay.',
    createdAt: '2026-05-21T14:08:00.000Z',
    helpfulCount: 164,
  },
  {
    id: 'rev-0029',
    productId: 'prd-0028',
    authorName: 'Aisha K.',
    verifiedPurchase: true,
    score: 4,
    title: 'Stabilisation claim is honest',
    body: 'Seven stops is optimistic in practice but five is reliable, which is still remarkable. Weather sealing survived a genuinely wet weekend in Snowdonia.',
    createdAt: '2026-02-26T11:55:00.000Z',
    helpfulCount: 71,
  },
  {
    id: 'rev-0030',
    productId: 'prd-0028',
    authorName: 'Jonah P.',
    verifiedPurchase: true,
    score: 3,
    title: 'Menus are dated',
    body: 'The sensor and body are excellent. The menu system looks and behaves like it was designed in 2012 and takes real effort to learn.',
    createdAt: '2025-10-30T16:42:00.000Z',
    helpfulCount: 89,
  },

  // ---------- Kestrel Nomad Portable Speaker ----------
  {
    id: 'rev-0031',
    productId: 'prd-0012',
    authorName: 'Sinead F.',
    verifiedPurchase: true,
    score: 5,
    title: 'Replaceable battery in a Bluetooth speaker',
    body: 'My last two speakers died because the battery did and could not be changed. Four screws and a twenty pound cell means this one should outlast them both.',
    createdAt: '2026-07-04T17:29:00.000Z',
    helpfulCount: 126,
  },
  {
    id: 'rev-0032',
    productId: 'prd-0012',
    authorName: 'Declan M.',
    verifiedPurchase: true,
    score: 4,
    title: 'Great outdoors, boomy indoors',
    body: 'On a beach or in a garden it sounds excellent. In a small tiled kitchen the bass gets overwhelming and there is no EQ to tame it.',
    createdAt: '2026-05-16T12:13:00.000Z',
    helpfulCount: 43,
  },

  // ---------- Solace Grind 40 ----------
  {
    id: 'rev-0033',
    productId: 'prd-0039',
    authorName: 'Patrick H.',
    verifiedPurchase: true,
    score: 5,
    title: 'Burrs come out without tools',
    body: 'Cleaning a grinder is the job you avoid, and this one takes about a minute. Grind consistency at espresso settings is well beyond what I paid for.',
    createdAt: '2026-06-09T08:26:00.000Z',
    helpfulCount: 78,
  },
  {
    id: 'rev-0034',
    productId: 'prd-0039',
    authorName: 'Anon',
    verifiedPurchase: false,
    score: 2,
    title: 'Static makes a mess',
    body: 'Grounds cling to everything and jump out of the catch cup. A drop of water on the beans helps but I should not need the trick at this price.',
    createdAt: '2026-03-30T07:41:00.000Z',
    helpfulCount: 95,
  },

  // ---------- Ferrite Glide Wireless Mouse ----------
  {
    id: 'rev-0035',
    productId: 'prd-0026',
    authorName: 'Vikram S.',
    verifiedPurchase: true,
    score: 5,
    title: 'Light without holes in it',
    body: 'Fifty-eight grams and a solid shell. Every other mouse this light looks like a cheese grater and collects crumbs. Wrist pain gone after a fortnight.',
    createdAt: '2026-07-31T19:16:00.000Z',
    helpfulCount: 109,
  },
  {
    id: 'rev-0036',
    productId: 'prd-0026',
    authorName: 'Freya T.',
    verifiedPurchase: true,
    score: 4,
    title: 'Battery claim holds up',
    body: 'Ninety hours is roughly right at 1000 Hz polling. Shape suits a claw grip better than a palm grip, which is not stated clearly enough.',
    createdAt: '2026-04-12T10:33:00.000Z',
    helpfulCount: 36,
  },

  // ---------- Lumina Glow bulbs ----------
  {
    id: 'rev-0037',
    productId: 'prd-0043',
    authorName: 'Oliver N.',
    verifiedPurchase: true,
    score: 5,
    title: 'Works with the internet unplugged',
    body: 'Tested it: pulled the router out and the schedules kept running. After being burned by a discontinued cloud service, this is the only way I will buy smart bulbs now.',
    createdAt: '2026-06-15T20:04:00.000Z',
    helpfulCount: 148,
  },
  {
    id: 'rev-0038',
    productId: 'prd-0043',
    authorName: 'Anon',
    verifiedPurchase: false,
    score: 3,
    title: 'Colour accuracy is average',
    body: 'Whites are lovely. Saturated colours, particularly deep reds, look washed out compared with the packaging. Fine for ambience, not for anything precise.',
    createdAt: '2026-02-03T18:47:00.000Z',
    helpfulCount: 54,
  },

  // ---------- Marlow USB-C cable ----------
  {
    id: 'rev-0039',
    productId: 'prd-0047',
    authorName: 'Grace L.',
    verifiedPurchase: true,
    score: 5,
    title: 'A USB-C cable that actually carries data',
    body: 'Most 240 W cables are charge-only and never say so. This does 40 Gbps and drove my monitor at 4K over the same lead. Labelled honestly, which is rare.',
    createdAt: '2026-08-09T09:58:00.000Z',
    helpfulCount: 87,
  },
  {
    id: 'rev-0040',
    productId: 'prd-0047',
    authorName: 'Adam Q.',
    verifiedPurchase: true,
    score: 4,
    title: 'Stiff for the first month',
    body: 'The braiding holds a coil memory out of the packet. It relaxed eventually. No complaints about performance.',
    createdAt: '2026-05-24T14:22:00.000Z',
    helpfulCount: 22,
  },
];
